version: '3'

services:
  expomorro-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: expomorro-api
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '1337:1337'
    command: yarn develop

